### ISSUE TITLE
Could you please elaborate on how the data is fed into the network?

### ISSUE THREAD

**Issue by brillianti** [chaofengc/QuanTexSR#3]
I'm trying to reproduce your model, but I'm not very clear on how to input the image and how many size dimensions need to be input.
Thank you!

**Comment by brillianti** [comment]
In addition, when I try to run QuanTexsr, cuda out of memory often occurs, even if I use RTX A6000, is there any way to solve it?

**Comment by chaofengc** [comment]
### For testing
you may simply follow the instructions in README after downloading pretrained QuanTexSR model:
```
python inference_quantexsr.py -w ./path/to/model/weight -i ./path/to/test/image[or folder]
```
### For training

#### Prior knowledge

The codebase is borrowed from [BasicSR](https://github.com/xinntao/BasicSR). I suggest you to read the the basicsr tutorial on [zhihu](https://www.zhihu.com/column/c_1295528110138163200) first to get a general understanding of the codebase. There are also lots of other Chinese blogs about using this codebase.

#### Model training

To retrain the model, you need to modify the option files under the `option/` folder.  There are three training stages, please follow detailed descriptions in the paper to reproduce each of them. You may also retrain the LQ stage only.

### Memory requirement

I am not sure why you cannot run the code on RTX A6000. The model should test well on a 3090 GPU with 24GB memory using any size of image as input because we split large photos into small patches.

https://github.com/chaofengc/QuanTexSR/blob/dae5edc9bf1ce0544db2f880e95eb8ce56d58a5e/inference_quantexsr.py#L58-L64

The provided training should also work well on 3090 GPU with 24GB memory using the provided option file.
```
python basicsr/train.py -opt options/train_QuanTexSR_LQ_stage.yml
```

**Comment by brillianti** [comment]
> 
Thank you for your reply! your third point reminded me that you are 600*600 in the inference_quantexsr.py file, but 8000*8000 around line 249 in the qsr_model.py, so I keep getting an error of cuda out of memory in validation, may I ask you here does 8000*8000 have any specific meaning? If not, I suggest changing it to 600*600.

**Comment by brillianti** [comment]
> ### For testing
> you may simply follow the instructions in README after downloading pretrained QuanTexSR model:
> 
> ```
> python inference_quantexsr.py -w ./path/to/model/weight -i ./path/to/test/image[or folder]
> ```
> 
> ### For training
> #### Prior knowledge
> The codebase is borrowed from [BasicSR](https://github.com/xinntao/BasicSR). I suggest you to read the the basicsr tutorial on [zhihu](https://www.zhihu.com/column/c_1295528110138163200) first to get a general understanding of the codebase. There are also lots of other Chinese blogs about using this codebase.
> 
> #### Model training
> To retrain the model, you need to modify the option files under the `option/` folder. There are three training stages, please follow detailed descriptions in the paper to reproduce each of them. You may also retrain the LQ stage only.
> 
> ### Memory requirement
> I am not sure why you cannot run the code on RTX A6000. The model should test well on a 3090 GPU with 24GB memory using any size of image as input because we split large photos into small patches.
> 
> https://github.com/chaofengc/QuanTexSR/blob/dae5edc9bf1ce0544db2f880e95eb8ce56d58a5e/inference_quantexsr.py#L58-L64
> 
> The provided training should also work well on 3090 GPU with 24GB memory using the provided option file.
> 
> ```
> python basicsr/train.py -opt options/train_QuanTexSR_LQ_stage.yml
> ```
Thank you for your reply! your third point reminded me that you are 600 * 600 in the inference_quantexsr.py file, but 8000 * 8000 around line 249 in the qsr_model.py, so I keep getting an error of cuda out of memory in validation, may I ask you here does 80008000 have any specific meaning? If not, I suggest changing it to 600600.

**Comment by brillianti** [comment]
Thanks for your reply! I have found the problem. The third point in your reply reminded me that you set 600 * 600 in QuanTexSR/inference_quantexsr.py, but in qsr_model.py you set 8000 * 8000 in line 249, so you can tell me to set 8000 * 8000 here what is the meaning? If not, I suggest setting it to 600 * 600.

**Comment by chaofengc** [comment]
No special meaning. I just disable patch inference for inference speed because there are no memory problem during train and validation. You may modify it as you want.
